RegisterCommand("search", function(source, args, raw)
    TriggerEvent("SearchPlayer")
end, false)

RegisterCommand("vsearch", function(source, args, raw)
    TriggerEvent("SearchVehicle")
end, false)

RegisterCommand("cpr", function(source, args, raw)
    TriggerEvent("GiveCPR")
end, false)

RegisterCommand("stand", function(source, args, raw)
    TriggerEvent("StandUp")
end, false)

RegisterNetEvent("SearchPlayer")
AddEventHandler("SearchPlayer", function(inputText) 
RequestAnimDict("anim@gangops@facility@servers@bodysearch@")
RequestAnimDict("amb@medic@standing@kneel@base")
TaskPlayAnim(GetPlayerPed(-1), "anim@gangops@facility@servers@bodysearch@" ,"player_search" ,8.0, -8.0, -1, 48, 0, false, false, false )
Citizen.Wait(1425)
TaskPlayAnim(GetPlayerPed(-1), "amb@medic@standing@kneel@base" ,"base" ,8.0, -8.0, -1, 1, 0, false, false, false )
TaskPlayAnim(GetPlayerPed(-1), "anim@gangops@facility@servers@bodysearch@" ,"player_search" ,8.0, -8.0, -1, 48, 0, false, false, false )
Citizen.Wait(5000)
ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent("SearchVehicle")
AddEventHandler("SearchVehicle", function(inputText) 
RequestAnimDict("anim@gangops@facility@servers@bodysearch@")
TaskPlayAnim(GetPlayerPed(-1), "anim@gangops@facility@servers@bodysearch@" ,"player_search" ,8.0, -8.0, -1, 48, 0, false, false, false )
Citizen.Wait(5000)
TaskPlayAnim(GetPlayerPed(-1), "anim@gangops@facility@servers@bodysearch@" ,"player_search" ,8.0, -8.0, -1, 48, 0, false, false, false )
Citizen.Wait(5000)
ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent("GiveCPR")
AddEventHandler("GiveCPR", function(inputText) 
RequestAnimDict("anim@gangops@facility@servers@bodysearch@")
RequestAnimDict("amb@medic@standing@kneel@base")
TaskPlayAnim(GetPlayerPed(-1), "amb@medic@standing@kneel@base" ,"base" ,8.0, -8.0, -1, 1, 0, false, false, false )
TaskPlayAnim(GetPlayerPed(-1), "anim@gangops@facility@servers@bodysearch@" ,"player_search" ,8.0, -8.0, -1, 48, 0, false, false, false )
Citizen.Wait(5000)
end)

RegisterNetEvent("StandUp")
AddEventHandler("StandUp", function(inputText) 
ClearPedTasksImmediately(GetPlayerPed(-1))
end)