resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

files {
	'data/visualsettings.dat',
	'data/cloudkeyframes.xml',
	'data/clouds.xml',
	'data/cpqsmix_ssaosettings.xml',
	'data/dlclist.xml',
	'data/gameconfig.xml',
	'data/hbaosettings.xml',
	'data/lensflare_f.xml',
	'data/lensflare_m.xml',
	'data/lensflare_t.xml',
	'data/playerinfo.xml',
	'data/playerswitch.meta',
	'data/watertune.xml',
	'data/effects/decals.dat',
	'data/effects/firefx.dat',
	'data/effects/vfxlightningsettings.xml',
	'data/levels/gta5/weather/blizzard_emitter_mist.xml',
	'data/levels/gta5/weather/blizzard_render_mist.xml',
	'data/levels/gta5/weather/desert_emitter_ground_heavy.xml',
	'data/levels/gta5/weather/desert_render_ground.xml',
	'data/levels/gta5/weather/desert_render_ground_heavy.xml',
	'data/levels/gta5/weather/rainstorm_render_ground.xml',
	'data/levels/gta5/weather/snowheavy_emitter_ground.xml',
	'data/levels/gta5/weather/snowheavy_render_ground.xml',
	'data/levels/gta5/time.xml',
	'data/levels/gta5/trains.xml',
	'data/levels/gta5/traintracks.xml',
	'data/levels/gta5/weather.xml',
	'data/timecycle/timecycle_mods_1.xml',
	'data/timecycle/timecycle_mods_2.xml',
	'data/timecycle/timecycle_mods_3.xml',
	'data/timecycle/timecycle_mods_4.xml',
	'data/timecycle/underwater_deep.xml',
	'data/timecycle/w_blizzard.xml',
	'data/timecycle/w_clear.xml',
	'data/timecycle/w_clearing.xml',
	'data/timecycle/w_clouds.xml',
	'data/timecycle/w_extrasunny.xml',
	'data/timecycle/w_foggy.xml',
	'data/timecycle/w_halloween.xml',
	'data/timecycle/w_neutral.xml',
	'data/timecycle/w_overcast.xml',
	'data/timecycle/w_rain.xml',
	'data/timecycle/w_smog.xml',
	'data/timecycle/w_snow.xml',
	'data/timecycle/w_snowlight.xml',
	'data/timecycle/w_thunder.xml',
	'data/timecycle/w_xmas.xml',
	'data/ui/mapzoomdata.meta',
	'data/ui/pausemenu.xml',
}




this_is_a_map 'yes'