-- CONFIG --

-- Blacklisted weapons
weaponblacklist = {
	"WEAPON_KNIFE",
	"WEAPON_NIGHTSTICK",
	"WEAPON_HAMMER",
	"WEAPON_BAT",
	"WEAPON_GOLFCLUB",
	"WEAPON_CROWBAR",
	"WEAPON_PISTOL",
	"WEAPON_COMBATPISTOL",
	"WEAPON_APPISTOL",
	"WEAPON_PISTOL50",
	"WEAPON_MICROSMG",
	"WEAPON_SMG",
	"WEAPON_ASSAULTSMG",
	"WEAPON_ASSAULTRIFLE",
	"WEAPON_CARBINERIFLE",
	"WEAPON_ADVANCEDRIFLE",
	"WEAPON_MG",
	"WEAPON_COMBATMG",
	"WEAPON_PUMPSHOTGUN",
	"WEAPON_SAWNOFFSHOTGUN",
	"WEAPON_ASSAULTSHOTGUN",
	"WEAPON_BULLPUPSHOTGUN",
	"WEAPON_STUNGUN",
	"WEAPON_SNIPERRIFLE",
	"WEAPON_HEAVYSNIPER",
	"WEAPON_REMOTESNIPER",
	"WEAPON_GRENADELAUNCHER",
	"WEAPON_GRENADELAUNCHER_SMOKE",
	"WEAPON_RPG",
	"WEAPON_PASSENGER_ROCKET",
	"WEAPON_AIRSTRIKE_ROCKET",
	"WEAPON_STINGER",
	"WEAPON_MINIGUN",
	"WEAPON_GRENADE",
	"WEAPON_STICKYBOMB",
	"WEAPON_SMOKEGRENADE",
	"WEAPON_BZGAS",
	"WEAPON_MOLOTOV",
	"WEAPON_FLARE",
	"WEAPON_VEHICLE_ROCKET",
	"WEAPON_SNSPISTOL",
	"WEAPON_BOTTLE",
	"WEAPON_GUSENBERG",
	"WEAPON_SPECIALCARBINE",
	"WEAPON_HEAVYPISTOL",
	"WEAPON_BULLPUPRIFLE",
	"WEAPON_DAGGER",
	"WEAPON_VINTAGEPISTOL",
	"WEAPON_FIREWORK",
	"WEAPON_MUSKET",
	"WEAPON_HEAVYSHOTGUN",
	"WEAPON_MARKSMANRIFLE",
	"WEAPON_HOMINGLAUNCHER",
	"WEAPON_PROXMINE",
	"WEAPON_FLAREGUN",
	"WEAPON_GARBAGEBAG",
	"WEAPON_COMBATPDW",
	"WEAPON_MARKSMANPISTOL",
	"WEAPON_KNUCKLE",
	"WEAPON_HATCHET",
	"WEAPON_RAILGUN",
	"WEAPON_MACHETE",
	"WEAPON_MACHINEPISTOL",
	"WEAPON_AIR_DEFENCE_GUN",
	"WEAPON_SWITCHBLADE",
	"WEAPON_REVOLVER",
	"WEAPON_DBSHOTGUN",
	"WEAPON_COMPACTRIFLE",
	"WEAPON_AUTOSHOTGUN",
	"WEAPON_BATTLEAXE",
	"WEAPON_COMPACTLAUNCHER",
	"WEAPON_MINISMG",
	"WEAPON_PIPEBOMB",
	"WEAPON_POOLCUE",
	"WEAPON_WRENCH",
	"VEHICLE_WEAPON_TANK",
	"VEHICLE_WEAPON_SPACE_ROCKET",
	"VEHICLE_WEAPON_PLANE_ROCKET",
	"VEHICLE_WEAPON_PLAYER_LAZER",
	"VEHICLE_WEAPON_PLAYER_LASER",
	"VEHICLE_WEAPON_PLAYER_BULLET",
	"VEHICLE_WEAPON_PLAYER_BUZZARD",
	"VEHICLE_WEAPON_PLAYER_HUNTER",
	"VEHICLE_WEAPON_ENEMY_LASER",
	"VEHICLE_WEAPON_SEARCHLIGHT",
	"VEHICLE_WEAPON_RADAR",
	"VEHICLE_WEAPON_WATER_CANNON",
	"VEHICLE_WEAPON_TURRET_INSURGENT",
	"VEHICLE_WEAPON_TURRET_TECHNICAL",
	"VEHICLE_WEAPON_NOSE_TURRET_VALKYRIE",
	"VEHICLE_WEAPON_PLAYER_SAVAGE",
	"VEHICLE_WEAPON_TURRET_LIMO",
	"VEHICLE_WEAPON_CANNON_BLAZER",
	"VEHICLE_WEAPON_TURRET_BOXVILLE",
	"VEHICLE_WEAPON_RUINER_BULLET",
	
}

-- Don't allow any weapons at all (overrides the blacklist)
disableallweapons = true

-- CODE --

Citizen.CreateThread(function()
	while true do
		Wait(1)

		playerPed = GetPlayerPed(-1)
		if playerPed then
			nothing, weapon = GetCurrentPedWeapon(playerPed, true)

			if disableallweapons then
				RemoveAllPedWeapons(playerPed, true)
			else
				if isWeaponBlacklisted(weapon) then
					RemoveWeaponFromPed(playerPed, weapon)
					sendForbiddenMessage("This weapon is blacklisted!")
				end
			end
		end
	end
end)

function isWeaponBlacklisted(model)
	for _, blacklistedWeapon in pairs(weaponblacklist) do
		if model == GetHashKey(blacklistedWeapon) then
			return true
		end
	end

	return false
end